CONFIG_NAME: 'oonetestnet'
PRESET_BASE: 'oonetestnet'

# Minimal preset - Phase0

# Misc
# ---------------------------------------------------------------
# [customized] Just 4 committees for slot for testing purposes
MAX_COMMITTEES_PER_SLOT: 4
# [customized] insecure, but fast (4)
TARGET_COMMITTEE_SIZE: 1
# 2**11 (= 2,048)
MAX_VALIDATORS_PER_COMMITTEE: 2048
# [customized] Faster, but insecure.
SHUFFLE_ROUND_COUNT: 2

# control how a validator's "effective balance" changes
# 4
HYSTERESIS_QUOTIENT: 4
# 1 (minus 0.25)
HYSTERESIS_DOWNWARD_MULTIPLIER: 1
# 5 (plus 1.25)
HYSTERESIS_UPWARD_MULTIPLIER: 5

# Fork Choice
# ---------------------------------------------------------------
# 2**1 (= 1)
# NOT FOUND IN ANNOTATED SPEC - in mainnet it's 8
SAFE_SLOTS_TO_UPDATE_JUSTIFIED: 2

# Gwei values
# same for mainnet - won't matter for us
# ---------------------------------------------------------------
# 2**0 * 10**9 (= 1,000,000,000) Gwei
MIN_DEPOSIT_AMOUNT: 1000000000
# 2**5 * 10**9 (= 32,000,000,000) Gwei
MAX_EFFECTIVE_BALANCE: 32000000000
# 2**0 * 10**9 (= 1,000,000,000) Gwei
EFFECTIVE_BALANCE_INCREMENT: 1000000000

# Time parameters
# ---------------------------------------------------------------
# 2**0 (= 1) slots 6 seconds
MIN_ATTESTATION_INCLUSION_DELAY: 1
# [customized] fast epochs
# OVERWRITTEN in our own configuration
# SLOTS_PER_EPOCH: 8
# 2**0 (= 1) epochs - controls the seed for choosing the committees
MIN_SEED_LOOKAHEAD: 1
# 2**2 (= 4) epochs - controls the seed for choosing the committees
MAX_SEED_LOOKAHEAD: 4
# [customized] higher frequency new deposits from eth1 for testing
EPOCHS_PER_ETH1_VOTING_PERIOD: 4
# [customized] smaller state
# controls history storage of the beacon chain
SLOTS_PER_HISTORICAL_ROOT: 64
# 2**2 (= 4) epochs
# epochs until the validator inactivity penalty kicks in
MIN_EPOCHS_TO_INACTIVITY_PENALTY: 4


# State list lengths
# controls history state lists
# ---------------------------------------------------------------
# [customized] smaller state
EPOCHS_PER_HISTORICAL_VECTOR: 64
# [customized] smaller state
EPOCHS_PER_SLASHINGS_VECTOR: 64
# 2**24 (= 16,777,216) historical roots
HISTORICAL_ROOTS_LIMIT: 16777216
# 2**40 (= 1,099,511,627,776) validator spots
VALIDATOR_REGISTRY_LIMIT: 1099511627776


# Reward and penalty quotients
# ---------------------------------------------------------------
# 2**6 (= 64)
BASE_REWARD_FACTOR: 64
# 2**9 (= 512)
WHISTLEBLOWER_REWARD_QUOTIENT: 512
# 2**3 (= 8)
PROPOSER_REWARD_QUOTIENT: 8
# [customized] 2**25 (= 33,554,432)
INACTIVITY_PENALTY_QUOTIENT: 33554432
# [customized] 2**6 (= 64)
MIN_SLASHING_PENALTY_QUOTIENT: 64
# [customized] 2 (lower safety margin than Phase 0 genesis but different than mainnet config for testing)
PROPORTIONAL_SLASHING_MULTIPLIER: 2


# Minimal preset - Altair

# Updated penalty values
# ---------------------------------------------------------------
# 3 * 2**24 (= 50,331,648)
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
# 2**6 (= 64)
MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
# 2
PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2

# Sync committee
# ---------------------------------------------------------------
# [customized]
# minimal value was 32
SYNC_COMMITTEE_SIZE: 1
# [customized]
# how much time until the sync committee changes
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256

# Sync protocol - NOT FOUND IN ANNOTATED SPEC
# ---------------------------------------------------------------
# 1
MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
# SLOTS_PER_EPOCH * EPOCHS_PER_SYNC_COMMITTEE_PERIOD (= 8 * 8)
UPDATE_TIMEOUT: 64

# Max operations per block
# ---------------------------------------------------------------
# 2**4 (= 16)
MAX_PROPOSER_SLASHINGS: 16
# 2**1 (= 2)
MAX_ATTESTER_SLASHINGS: 2
# 2**7 (= 128)
MAX_ATTESTATIONS: 128
# 2**4 (= 16)
MAX_DEPOSITS: 16
# 2**4 (= 16)
MAX_VOLUNTARY_EXITS: 16

# Minimal preset - Bellatrix

# Updated penalty values
# ---------------------------------------------------------------
# 2**24 (= 16,777,216)
INACTIVITY_PENALTY_QUOTIENT_BELLATRIX: 16777216
# 2**5 (= 32)
MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX: 32
# 3
PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX: 3

# Execution
# ---------------------------------------------------------------
# 2**30 (= 1,073,741,824)
MAX_BYTES_PER_TRANSACTION: 1073741824
# 2**20 (= 1,048,576)
MAX_TRANSACTIONS_PER_PAYLOAD: 1048576
# 2**8 (= 256)
BYTES_PER_LOGS_BLOOM: 256
# 2**5 (= 32)
MAX_EXTRA_DATA_BYTES: 32

# ACTUAL CONFIG

# Transition
# ---------------------------------------------------------------
# 2**256-2**10 for testing minimal network

# TERMINAL_TOTAL_DIFFICULTY:
# 115792089237316195423570985008687907853269984665640564039457584007913129638912
TERMINAL_TOTAL_DIFFICULTY: 50

# NOT NEEDED since the TERMINAL_TOTAL_DIFFICULTY is enough to determine when the chain should switch to PoS: https://eth2book.info/bellatrix/annotated-spec/
# By default, don't use these params
# TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Genesis
# ---------------------------------------------------------------
# [customized]
# 64
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
# Jan 3, 2020
MIN_GENESIS_TIME: 1578009600
# Highest byte set to 0x01 to avoid collisions with mainnet versioning
# 0x00000001
GENESIS_FORK_VERSION: 0x20000089
# [customized] Faster to spin up testnets, but does not give validator reasonable warning time for genesis
GENESIS_DELAY: 3

# Forking
# ---------------------------------------------------------------
# Values provided for illustrative purposes.
# Individual tests/testnets may set different values.

# Altair
# 0x01000001
ALTAIR_FORK_VERSION: 0x20000090
# 18446744073709551615
ALTAIR_FORK_EPOCH: 2
# Bellatrix
# 0x02000001
BELLATRIX_FORK_VERSION: 0x20000091
# 18446744073709551615
BELLATRIX_FORK_EPOCH: 4
# Capella
# CAPELLA_FORK_VERSION: 0x03000001
# CAPELLA_FORK_EPOCH: 18446744073709551615
# EIP4844
# EIP4844_FORK_VERSION: 0x04000001
# EIP4844_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
# [customized] Faster for testing purposes
SECONDS_PER_SLOT: 6
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs
# 256
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 0
# [customized] higher frequency of committee turnover and faster time to acceptable voluntary exit
# 64
SHARD_COMMITTEE_PERIOD: 0
# [customized] process deposits more quickly, but insecure
ETH1_FOLLOW_DISTANCE: 16
# [customized] fast epochs
# overrides phase0 preset value of 8
SLOTS_PER_EPOCH: 6

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# [customized] scale queue churn at much lower validator counts for testing
CHURN_LIMIT_QUOTIENT: 32

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 123456
# Configured on a per testnet basis
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242