CONFIG_NAME: 'oonetestnet'
PRESET_BASE: 'oonetestnet'

# Execution
# ---------------------------------------------------------------
# 2**30 (= 1,073,741,824)
MAX_BYTES_PER_TRANSACTION: 1073741824
# 2**20 (= 1,048,576)
MAX_TRANSACTIONS_PER_PAYLOAD: 1048576
# 2**8 (= 256)
BYTES_PER_LOGS_BLOOM: 256
# 2**5 (= 32)
MAX_EXTRA_DATA_BYTES: 32

# ACTUAL CONFIG

# Transition
# ---------------------------------------------------------------
# 2**256-2**10 for testing minimal network

# TERMINAL_TOTAL_DIFFICULTY:
# 115792089237316195423570985008687907853269984665640564039457584007913129638912
TERMINAL_TOTAL_DIFFICULTY: 50

# NOT NEEDED since the TERMINAL_TOTAL_DIFFICULTY is enough to determine when the chain should switch to PoS: https://eth2book.info/bellatrix/annotated-spec/
# By default, don't use these params
# TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
# TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Genesis
# ---------------------------------------------------------------
# [customized]
# 64
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
# Jan 3, 2020
MIN_GENESIS_TIME: 1578009600
# Highest byte set to 0x01 to avoid collisions with mainnet versioning
# 0x00000001
GENESIS_FORK_VERSION: 0x20000089
# [customized] Faster to spin up testnets, but does not give validator reasonable warning time for genesis
GENESIS_DELAY: 3

# Forking
# ---------------------------------------------------------------
# Values provided for illustrative purposes.
# Individual tests/testnets may set different values.

# Altair
# 0x01000001
ALTAIR_FORK_VERSION: 0x20000090
# 18446744073709551615
ALTAIR_FORK_EPOCH: 2
# Bellatrix
# 0x02000001
BELLATRIX_FORK_VERSION: 0x20000091
# 18446744073709551615
BELLATRIX_FORK_EPOCH: 4
# Capella
# CAPELLA_FORK_VERSION: 0x03000001
# CAPELLA_FORK_EPOCH: 18446744073709551615
# EIP4844
# EIP4844_FORK_VERSION: 0x04000001
# EIP4844_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
# [customized] Faster for testing purposes
SECONDS_PER_SLOT: 6
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs
# 256
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 0
# [customized] higher frequency of committee turnover and faster time to acceptable voluntary exit
# 64
SHARD_COMMITTEE_PERIOD: 0
# [customized] process deposits more quickly, but insecure
ETH1_FOLLOW_DISTANCE: 16
# [customized] fast epochs
# overrides phase0 preset value of 8
SLOTS_PER_EPOCH: 6

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# [customized] scale queue churn at much lower validator counts for testing
CHURN_LIMIT_QUOTIENT: 32

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 123456
# Configured on a per testnet basis
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242